=== yangqiaosheng/wmsbrowser/src/WMSOverview/Wms.Client/WmsServerDescriptors.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="WmsServerDescriptors" targetNamespace="http://learn.arc.nasa.gov/schemas/WmsServerDescriptors.xsd"
	elementFormDefault="qualified" xmlns="http://learn.arc.nasa.gov/schemas/WmsServerDescriptors.xsd"
	xmlns:mstns="http://learn.arc.nasa.gov/schemas/WmsServerDescriptors.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="WmsServerDescriptors">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Server" type="ServerDescriptor" maxOccurs="50" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ServerDescriptor">
		<xs:sequence>
			<xs:element name="Uri" type="xs:anyURI" />
			<xs:element name="Name" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== yangqiaosheng/wmsbrowser/src/WMSOverview/Wms.Client/DefaultServerDescriptors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<WmsServerDescriptors xmlns="http://learn.arc.nasa.gov/schemas/WmsServerDescriptors.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://learn.arc.nasa.gov/schemas/WmsServerDescriptors.xsd
D:\Sandbox\WMS\Wms.Client\WmsServerDescriptors.xsd">
	<Server>
		<Uri>http://viz.globe.gov/viz-bin/wmt.cgi</Uri>
		<Name>GLOBE Server</Name>
	</Server>
	<Server>
		<Uri>http://demo.cubewerx.com/demo/cubeserv/cubeserv.cgi</Uri>
		<Name>CubeSERV</Name>
	</Server>
	<Server>
		<Uri>http://wms.jpl.nasa.gov/gis-wms.cgi</Uri>
		<Name>JPL World Map Service</Name>
	</Server>
</WmsServerDescriptors>
